title: Tobar na h√âigse
description: A directory of Irish language resources
remote_theme: just-the-docs/just-the-docs
url: "https://draoi.github.io"
baseurl: "/tobar-na-heigse"
color_scheme: dark
search_enabled: true
back_to_top: false
footer_content: "Content licensed <a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" rel=\"license\">CC BY-NC 4.0</a>; code licensed <a href=\"https://opensource.org/licenses/MIT\">MIT</a>."
plugins:
  - jekyll-remote-theme
